### PR TITLE
Add basic search functionality to `NewProject` starter list

### PR DESCRIPTION
**Pull request by jwmza**
image
image

### CODE REVIEW

**Comment by jwmza** [comment]
Probably want to replace "Does the fist `n` letters match?" for `stringSimilarity` as we had in previous search lists.

**Comment by jwmza** [comment]
^ Same can be said for in `<DirectoryBrowser />` and all other similar search lists

**Comment by jwmza** [comment]
& Yes, colors swap semi-intelligently with theme:
image

**Comment by jwmza** [comment]
This has some Go code in it and I'm only 90% sure I did it correctly so please review @brandonbloom  :)

**Review by brandonbloom — APPROVED** [review]
This LGTM, including the Go code.

**Comment by jwmza** [comment]
Thanks @brandonbloom

**Comment by jwmza** [comment]
image

**Comment by jwmza** [comment]
There are still some logos missing, but there's a sensible default. Gonna merge now and focus on higher priority.

**Pull request merged**
