### PR TITLE
shortest unique root suffix as display name

### PR DESCRIPTION
**Pull request by brandonbloom**
Follow-up to #338 and in support of #335

### CODE REVIEW

**Review by jwmza — APPROVED** [review]
LGTM

@brandonbloom what is the reason for having something dynamic like `filepath.Separator`? is this an OS difference across devices?

**Comment by brandonbloom** [comment]
> what is the reason for having something dynamic like filepath.Separator?

I parameterized that so that I could use unix-style path separators (`/`) in the tests. Otherwise, the tests would have been broken on Windows, where the path separator is `\`.

**Comment by jwmza** [comment]
> > what is the reason for having something dynamic like filepath.Separator?
> 
> I parameterized that so that I could use unix-style path separators (`/`) in the tests. Otherwise, the tests would have been broken on Windows, where the path separator is `\`.

I thought we didn't support Windows at all @brandonbloom

**Comment by brandonbloom** [comment]
We likely will in the future. Mostly dropped windows support previously on a temporary basis to get an early release out.

**Comment by jwmza** [comment]
Gotcha. That's good to hear.

**Pull request merged**
