### PR TITLE
gui list of workspaces on home page

### PR DESCRIPTION
**Pull request by brandonbloom**
WIP for @jwmza to takeover and finish

### CODE REVIEW

**Comment by jwmza** [comment]
Auto-responsive grid layout to prevent ridiculously long boxes on big screens and allow devs to have dozens of workspaces if they so choose in a layout that also looks good with just a few!

image

**Comment by brandonbloom** [comment]
What is `default` here? Seems like you might have some leftover gunk from before workspaces were properly implemented. I suggest you use run `exo exit` and then `rm -rf ~/.exo`.

Also, my expectation is that most users will have one to a single-digit number of workspaces, but I guess in theory some users may have quite a few.

**Comment by brandonbloom** [comment]
i'm going to merge this as it's better than not having it, but i think the design needs another pass. thanks @jwmza

**Comment by jwmza** [comment]
Agreed thanks @brandonbloom

**Pull request merged**
