### PR TITLE
Add docs website

### PR DESCRIPTION
**Pull request by jwmza**
This adds a **Nextra + Typescript + Next.js** react web app to display documentation and moves our docs pages from `/doc/` to `/docs/pages` (mostly in order to appease Nextra).

image

---

You can develop & test this website like so:
```rb
$ cd docs
$ npm i
$ npm run dev
```
and opening `localhost:3000`

---

Once this PR is merged, I'll deploy the site to Vercel and fix all the links + add a "Docs" link to `exo.deref.io` before making it available at another subdomain. I'm thinking `exo-docs.deref.io` @brandonbloom

### CODE REVIEW

**Comment by brandonbloom** [comment]
Looking pretty good! A few quick comments:

1) kinda a bummer that the /docs directory had to have everything pushed down in to /docs/pages, but probably OK for now.
2) Instead of `exo-docs.deref.io`, is `docs.exo.deref.io` possible?
3) We should probably do a content pass before we deploy this. I'll block off some time early next week to make some tweaks to this branch for meta & the .md files.

Thanks!

**Comment by jwmza** [comment]
@brandonbloom 

> docs.exo.deref.io

I'm not sure, I'd prefer that as well but I guess we'll see what Vercel can do. I'll try this first.

> 1.

Yeah :/

> 3

Yep. There's still some remaining work to be done:

- [ ] Favicon needs to be added
- [ ] Links in the `.md` files need to be fixed such that they navigate between pages in this website. We might want a `...[page].md` to `...[page]` redirect, or just rewrite all the links with the assumption people view them on the docs site and not in the GitHub previews.
- [ ] It seems like Nextra is automatically creating tables of content for subsection headings but the links for these appear broken. I mean, you'll get linked to `.../page#subsection` but the `<h2>Subsection` doesn't get an `id` attribute so it doesn't scroll for you.
- [ ] Probably makes sense to import `prismjs` or something for syntax highlighting (I think Nextra has an easy example of this)

**Comment by brandonbloom** [comment]
OK, keep at it. We'll sync Monday morning.

**Comment by jwmza** [comment]
Also, after this is deployed, we should update the main `exo.deref.io` site to:

- Add a "Docs" link (to the top right, across from the main logo?)
- Update the e.g. `install.md` links in the landing page from pointing to the GitHub repo markdown preview to the docs website pages instead

**Comment by jwmza** [comment]
I have no idea why page section headings aren't getting `id` attributes, as mentioned above.

I've looked into **Nextra** and **SWR-site**'s own documentation websites and I see no relevant config difference which should cause their section headings to have proper `id` links but ours not to.

**Comment by brandonbloom** [comment]
closing, since we decided on gitbook

**Pull request closed without merging**
